config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#show'

  put '/billet_payments/:id/cancel', to: 'billet_payments#cancel'

  resources :customers, only: %i[new create]

  resources :addresses, only: %i[new create]

  resources :billet_payments
end

app/models/address.rb
# frozen_string_literal: true

# Model responsible for customer address data
class Address < ApplicationRecord
  belongs_to :customer

  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  validates :neighborhood, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

# General module for configuring things for models of system
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billet_payment.rb
# frozen_string_literal: true

# Model responsible for customer billet payments infos
class BilletPayment < ApplicationRecord
  belongs_to :customer

  validates :amount, presence: true
  validates :expire_at, presence: true

  validates :status, inclusion: { in: %w[opened overdue canceled paid],
                                  message: '%<value>s is not a valid status' }
end

app/models/customer.rb
# frozen_string_literal: true

# Model responsible for customer data
class Customer < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :billet_payments, dependent: :destroy

  validates :name, presence: true
  validates :document, presence: true
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

# Controller responsible for received the request to create customers addresses
class AddressesController < ApplicationController
  before_action :prepare_customer, only: [:new]

  def new
    @address = Address.new
  end

  def create
    result = Addresses::Create.call(address_params: address_params.merge(customer_id: params[:customer_id]))

    if result.success?
      redirect_to new_billet_payment_path(customer_id: result.address.customer.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def address_params
    params.permit(:address, :city, :state, :zipcode, :neighborhood)
  end

  def prepare_customer
    @customer_id = Customer.find(params[:customer_id]).id
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# General module for configuring things for controllers of system
class ApplicationController < ActionController::Base
end

app/controllers/billet_payments_controller.rb
# frozen_string_literal: true

# Controller responsible for received the main requests for billet_payment
class BilletPaymentsController < ApplicationController
  before_action :prepare_customer, only: [:new]
  before_action :find_billet, only: %i[show edit update]

  def index
    result = BilletPayments::ListApi.call

    @billet_payments = result.billet_payments.present? ? result.billet_payments : []
    flash[:alert] = result.message

    respond_to do |format|
      format.html
      format.json { render json: @billet_payments }
    end
  end

  def show; end

  def new
    @billet_payment = BilletPayment.new
  end

  def create
    result = BilletPayments::CreateOrganizer.call(
      billet_payments_params: billet_payments_params.merge(customer_id: params[:customer_id], status: 'opened')
    )

    if result.success?
      redirect_to billet_payment_path(result.billet_payment)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    result = BilletPayments::EditOrganizer.call(
      billet_payment: @billet_payment,
      customer_id: params[:customer_id],
      billet_payments_params:
    )

    if result.success?
      redirect_to billet_payment_path(result.billet_payment)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def cancel
    result = BilletPayments::CancelOrganizer.call(
      billet_payment_id: billet_payments_params[:id]
    )

    if result.success?
      redirect_to billet_payment_path(result.billet_payment)
    else
      find_billet
      render :show, status: :unprocessable_entity
    end
  end

  private

  def billet_payments_params
    params.permit(:amount, :status, :id)
  end

  def prepare_customer
    @customer_id = Customer.find(params[:customer_id]).id
  end

  def find_billet
    @billet_payment = BilletPayments::FindApi.call(billet_payment_id: params[:id]).billet_payment
  end
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

# Controller responsible for received the request to create customers
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    result = Customers::Create.call(customers_params: customer_params)

    if result.success?
      redirect_to new_address_path(customer_id: result.customer.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def customer_params
    params.permit(:name, :document)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Controller responsible for received the main requests for billet_payment
class HomeController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# General module for configuring things for helpers of system
module ApplicationHelper
end

app/views/addresses/new.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="">
    <div class="mx-auto lg:max-w-5xl md:max-w-2xl sm:max-w-xl">
      <div class="space-y-6 rounded border-4 border-lime-200 p-10 text-lg text-white">
        <h2 class="flex justify-center font-bold text-2xl">Endereço de Faturamento</h2>
        <%= form_with url: addresses_path(customer_id: @customer_id), method: :post, id: 'address_form' do |form| %>

          <div class="mb-4">
            <%= form.label :address, "Endereço", class: "mb-2 block font-bold" %>
            <%= form.text_field :address, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :city, "Cidade", class: "mb-2 block font-bold" %>
            <%= form.text_field :city, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :state, "Estado", class: "mb-2 block font-bold" %>
            <%= form.text_field :state, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :zipcode, "Cep", class: "mb-2 block font-bold" %>
            <%= form.text_field :zipcode, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :neighborhood, "Bairro", class: "mb-2 block font-bold" %>
            <%= form.text_field :neighborhood, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="flex items-center justify-center">
            <button class="rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" type="submit" form="address_form">Cadastrar Endereço</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/billet_payments/edit.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="">
    <div class="mx-auto lg:max-w-5xl md:max-w-2xl sm:max-w-xl">
      <div class="space-y-6 rounded border-4 border-lime-200 p-10 text-lg text-white">
        <h2 class="flex justify-center font-bold text-2xl">Atualizar Boleto</h2>
        <%= form_with url: billet_payment_path, method: :patch, id: "billet_payment_update_form" do |form| %>
          <div class="mb-4">
            <%= form.label :amount, "Valor", class: "mb-2 block font-bold" %>
            <%= form.number_field :amount, value: @billet_payment["amount"] , class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :expire_at, "Expira em:", class: "mb-2 block font-bold" %>
            <%= form.number_field :expire_at, value: @billet_payment["expire_at"] , class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="flex items-center justify-center">
            <button class="rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" type="submit" form="billet_payment_update_form">Atualizar Boleto</button>
          </div>
        <% end %>
     </div>
    </div>
  </div>
</div>

app/views/billet_payments/index.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="flex flex-col justify-content">
    <% flash.each do |nome, mensagem| %>
      <%= content_tag :div, mensagem, class: nome %>
    <% end %>
    <div class="mx-auto space-y-8 sm:max-w-xl md:max-w-2xl lg:max-w-7xl">
      <div class="relative overflow-x-auto">
        <table>
          <thead class="text-xs uppercase text-white">
            <tr class="border-2 border-lime-200">
              <th scope="col" class="px-6 py-3">Id</th>
              <th scope="col" class="px-6 py-3">Valor</th>
              <th scope="col" class="px-6 py-3">Expira em</th>
              <th scope="col" class="px-6 py-3">Nome do consumidor</th>
              <th scope="col" class="px-6 py-3">Status</th>
              <th scope="col" class="px-6 py-3"></th>
            </tr>
          </thead>
          <tbody>
            <% @billet_payments.each do |billet| %>
              <tr class="border border-lime-200 text-white">
                <th scope="row" class="whitespace-nowrap px-6 py-4 font-medium"><%= billet["id"] %></th>
                <td class="px-6 py-4">R$<%= billet["amount"] %></td>
                <td class="px-6 py-4"><%= billet["expire_at"] %></td>
                <td class="px-6 py-4"><%= billet["customer_person_name"] %></td>
                <td class="px-6 py-4"><%= billet["status"] %></td>
                <td class="px-6 py-4">
                  <%= link_to "Ver", billet_payment_path(billet["id"]), class: "rounded px-4 py-2 font-bold text-white hover:text-lime-200 hover:underline hover:underline-offset-2 focus:outline-none" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="flex items-center justify-center">
        <%= link_to "Cadastrar", new_customer_path, class: "rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" %>
      </div>
    </div>
  </div>
</div>

app/views/billet_payments/new.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="">
    <div class="mx-auto lg:max-w-5xl md:max-w-2xl sm:max-w-xl">
      <div class="space-y-6 rounded border-4 border-lime-200 p-10 text-lg text-white">
        <h2 class="flex justify-center font-bold text-2xl">Endereço de Faturamento</h2>
        <%= form_with url: billet_payments_path(customer_id: @customer_id), method: :post, id: 'billet_payment_form' do |form| %>
          <div class="mb-4">
            <%= form.label :amount, "Valor", class: "mb-2 block font-bold" %>
            <%= form.number_field :amount, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="flex items-center justify-center">
            <button class="rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" type="submit" form="billet_payment_form">Cadastrar Boleto</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/billet_payments/show.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="">
    <div class="mx-auto lg:max-w-5xl md:max-w-2xl sm:max-w-xl">
      <div class="space-y-6 rounded border-4 border-lime-200 p-10 text-lg text-white">
        <div>
          <h2 class="flex justify-center font-bold text-2xl">Dados</h2>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Nome do consumidor: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_person_name"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Número do documento: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_cnpj_cpf"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Valor: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["amount"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Endereço: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_address"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Cidade: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_city_name"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Estado: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_state"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Cep: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_zipcode"] %></p>
          </div>

          <div class="mb-4 flex space-x-10">
            <label class="mb-2 block font-bold" for="username"> Bairro: </label>
            <p class="mb-2 block" for="username"><%= @billet_payment["customer_neighborhood"] %></p>
          </div>
        </div>
        <div class="flex flex-col items-center space-y-10">
          <div class="flex space-x-4">
            <%= link_to "Editar", edit_billet_payment_path(@billet_payment), class: "rounded px-4 py-2 font-bold text-white hover:text-lime-200 hover:underline hover:underline-offset-2 focus:outline-none" %>

            <%= form_with url: "/billet_payments/#{@billet_payment.id}/cancel", method: :put, id: "billet_payment_update_form" do |form| %>
              <%= form.submit "Cancelar", class: "rounded px-4 py-2 font-bold text-white hover:text-lime-200 hover:underline hover:underline-offset-2 focus:outline-none" %>
            <% end %>
          </div>
          <div class="flex space-x-4">
            <div class="flex items-center justify-center">
              <%= link_to "Listagem", billet_payments_path, class: "rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="flex flex-col">
  <%= image_tag("logo.jpeg", class: "m-10") %>
  <div class="">
    <div class="mx-auto lg:max-w-5xl md:max-w-2xl sm:max-w-xl">
      <div class="space-y-6 rounded border-4 border-lime-200 p-10 text-lg text-white">
        <h2 class="flex justify-center font-bold text-2xl">Dados do Consumidor</h2>
        <%= form_with url: customers_path, method: :post, id: 'customer_form'  do |form| %>
          <div class="mb-4">
            <%= form.label :name, "Nome do consumidor:", class: "mb-2 block font-bold" %>
            <%= form.text_field :name, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="mb-4">
            <%= form.label :document, "Número do documento:", class: "mb-2 block font-bold" %>
            <%= form.text_field :document, class: "w-full rounded border border-lime-200 bg-black px-3 py-2 focus:border-2 focus:border-lime-300 focus:outline-none" %>
          </div>

          <div class="flex items-center justify-center">
            <button class="rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" type="submit" form="customer_form">Cadastrar Consumidor</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="relative flex min-h-screen flex-col justify-center bg-black py-6 text-white sm:py-12">
  <%= image_tag("logo.jpeg", class: "m-10") %>

  <div class="flex flex-col items-center space-y-20">
    <div class="flex flex-col items-center">
      <h2>Bem-vindo ao sistema de criação de boletos</h2>
      <h3>Se estiver pronto para começar, basta clicar em um dos dois botões abaixo</h3>
    </div>
    <div class="flex space-x-10">
      <%= link_to "Listar Boletos", billet_payments_path, class: "rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" %>
      <%= link_to "Cadastrar Boleto", new_customer_path, class: "rounded border-2 border-lime-200 px-4 py-2 font-bold text-white hover:bg-lime-200 focus:outline-none" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppBillet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="flex min-h-screen flex-col justify-center bg-black ">
      <%= yield %>
    </main>
  </body>
</html>